CREATE TABLE IF NOT EXISTS Product (
    ID VARCHAR(255) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Price INTEGER NOT NULL,
    Unit_ID INTEGER NOT NULL,
    Category_ID INTEGER NOT NULL,
    Created_At TIMESTAMP NOT NULL,
    Updated_At TIMESTAMP NOT NULL,
    Deleted_At TIMESTAMP NULL,
    FOREIGN KEY (Unit_ID) REFERENCES Unit(ID),
    FOREIGN KEY (Category_ID) REFERENCES Category(ID)
);